name: Gitleaks Organizational Scan
description: Starter workflow para escanear segredos com Gitleaks.
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  scan:
    name: Gitleaks
    # Adicionando este bloco para máxima segurança
    permissions:
      contents: read # A Action só precisa ler o conteúdo do código.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
